#!/bin/bash
#
#::                                          A D M I N   C O M M A N D
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// System managment Setup Script //::::::::::::::::::::::::::::// Ubuntu //:::::::
#::
#::     Author:   	SLS
#::     Version 	1.02
:	${GIT_Profile:=vonschutter}
#::
#::
#::	Purpose: The purpose of the script is to install and configure landscape for ubuntu so it can be managed from
#::		 a single location.
#::
#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
#:: 		Then, when prompted; enter the information requested.
#::
#::     	To understand how t use Landscape please refer to: https://landscape.canonical.com/
#::
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
#

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Functions                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

dependency::_rtd_library ()
{
	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/_rtd_library

	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../core/_rtd_library ; then
		write_information "${FUNCNAME[0]} 1 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../core/_rtd_library
	elif source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library ; then
		write_information "${FUNCNAME[0]} 2 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../core/_rtd_library
	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
		write_information "${FUNCNAME[0]} 3 Using: $(find /opt -name _rtd_library |grep -v bakup )"
	elif wget ${_src_url} ; then
                write_information "${FUNCNAME[0]} 4 Using: ${_src_url}"
		source ./_rtd_library
	else
		echo -e "RTD functions NOT found!"
		return 1
	fi
}




#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Executive                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

# Ensure access to the rtd library functions:
dependency::_rtd_library || { write_error "clamav not found!" ; exit 1 ; }
# Ensure elevated privs:
ensure_admin
# Ensure all updates are applied:
up2date
# Check that "dialog" is available:
check_dependencies dialog

# The name of the local managment server
LOCALSERVER=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"$( basename $0 )"}" --stdout --inputbox "\n Please enter the name of the local landscape server. \n " 10 90 )
LOCALSERVERIP=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"$( basename $0 )"}" --stdout --inputbox "\n Please enter the IP Address of the local landscape server. \n " 10 90 )

if [[ -z "${LOCALSERVER}" ]] || [[ -z "${LOCALSERVERIP}" ]]; then
	write_error "You must provide the name and IP address of the local landscape server!"
	exit 1
fi


if ! ping -c 1 ${LOCALSERVERIP} ; then
	write_error "The local landscape server ${LOCALSERVERIP} is not reachable!"
	exit 1
fi

if hostnamectl |grep -q "Operating System: Ubuntu" ; then
	write_information "This is an Ubuntu system."
	# Since landscape is only relevant for Ubuntu; its OK to use distro speciffic commands...
	add-apt-repository --update ppa:landscape/self-hosted-23.03 -y
	apt install landscape-server-quickstart -y
	echo "ssl_public_key = /etc/landscape/landscape_server_ca.crt" >>/etc/landscape/client.conf
	write_status "---------------- clinet.conf  -----------"
	write_information "$( cat /etc/landscape/client.conf )"
	echo "${LOCALSERVERIP}       ${LOCALSERVER}" >>/etc/hosts
	write_status "----------------  hosts -----------------"
	write_information "$( cat /etc/hosts )"
	write_status "---------  Get CA from ${LOCALSERVER} ---------"
	echo Enter password for ${LOCALSERVER} below:
	scp ${USER}@${LOCALSERVER}:/etc/landscape/*.crt /etc/landscape/
	landscape-config --computer-title "${HOSTNAME}" --account-name standalone  -p ${PASSTOKEN} --url https://${LOCALSERVER}/message-system --ping-url http://${LOCALSERVER}/ping && result="Sucessfully enrolled with the lanscape server ${LOCALSERVER}" || result="Failed to enroll with the lanscape server ${LOCALSERVER}"
	display_result "$( basename $0 )"

else
	write_error "This script is intended for Ubuntu systems only!"
	exit 1
fi


