#!/bin/bash
: <<'Script_Documentation'
                                          -    RTD Power Toy Script      -

:::::::::::::::::::::::::::::::::::::::::: PREVENT RUNING IN WINDOWS	 ::::::::::::::::::::::::::::::::::::::::::::::::

cls & color 0C & echo Do not attempt to run this script in CMD.EXE & pause & color 0F & exit /b

::::::::::::::::::::::::::::::::::::::::::::: HEADER DO NOT REMOVE ::::::::::::::::::::::::::::::::::::::::::::::::::::::



                                             A D M I N   C O M M A N D 
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::// Simple Compression Toy //::::::::::::::::::::::::::::// Linux //::::::::
::
:: 	Author:   	SLS
:: 	Version 	1.03
::
::
::	Purpose: To compress all files and folders individually found in the current folder.
::		 The current folder refers to the present working directory "PWD".
::
::	Usage:	Simply execute this script to accomplish this task. No parameters required.
::
::
::
::
::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


 This script is shared in the hopes that it will be useful.

 This script is part of the RTD Power Toy collection. The RTD Power Toy collection consists of scripts designed
 to be used together to accomplish a wide range of tasks. These scripts are simple, easy to use, and easy to
 understand, making them suitable for use in a Linux environment, though they may be adaptable to other environments.
 A special header is included to either prevent execution in Windows or to execute the proper section if run in Windows,
 thereby preventing accidental execution of the script in a Windows (CMD) environment and avoiding potential harm.

 For convenience and supportability, most actions (work) are stored in a common library used by multiple scripts.
 While using this library is optional, it may save time. Typically, if a function is useful in more than one script, 
 it is included in the library. This script demonstrates the ease of using these functions.
 To utilize these functions, simply load the library using the "source" bash built-in command. All
 functions will then be available for use.

 This script is intended to reside in the ~/bin/ or /bin/ directory, or alternatively, in the $PATH.
 By default, this script is placed in /opt/rtd/modules/{collection or name}.

 1 - To view options for using the RTD library, type: "bash _rtd_library --help"
 2 - To view detailed documentation for each function in this library, type: "bash _rtd_library --devhelp | --devhelp-gtk"

 Function: dependency::_library
 Description: This function ensures access to the RTD library functions by sourcing the appropriate script.
 It first sources the library from a relative path, then from ~/bin, and finally from the /opt directory. Using the 
 relative path is beneficial for development and testing, ~/bin is useful for user-specific scripts, and /opt 
 is suitable for system-wide scripts. Additionally, the function downloads the library from the GitHub repository 
 and sources it if it is not found in any of the  previous locations. If all attempts fail, it displays an error 
 message and returns 1.

 Function: compress_all_items_here
 Description: This function compresses all files and folders individually found in the current folder,
 which refers to the present working directory (PWD).

Script_Documentation




#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Settings                 ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Variables that govern the behavior or the script and location of files are
# set here. There should be no reason to change any of this abcent strong preferences.

:	${LIBFILE:="_rtd_library"} 	# The name of the library file.
:	${GIT_Profile:=vonschutter} 	# The name of the GitHub profile where the library is located.

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Functions                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

dependency::_library ()
{
	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/${LIBFILE}

	# Try to source the library from relative path, ~/bin, and finally from the /opt directory.
	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/${LIBFILE} ; then
		write_information "${FUNCNAME[0]} 2 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../core/${LIBFILE}
	elif source "$(find ${HOME}/bin -name ${LIBFILE} |grep -v bakup )" ; then
		write_information "${FUNCNAME[0]} 1 Using:  $(find ${HOME}/bin -name ${LIBFILE} |grep -v bakup )"
	elif source $(find /opt -name ${LIBFILE} |grep -v bakup ) ; then
		write_information "${FUNCNAME[0]} 3 Using: $(find /opt -name ${LIBFILE} |grep -v bakup )"
	elif wget ${_src_url} ; then
                write_information "${FUNCNAME[0]} 4 Using: ${_src_url}"
		source ./${LIBFILE}
	else
		echo -e "RTD functions NOT found!"
		return 1
	fi
}


local::_help ()
{
	echo -e "
	This script compresses all files and folders individually found in the current folder. 
	The current folder refers to the present working directory \"PWD\".
	
	Usage: Simply execute this script to accomplish this task. No parameters required.
	
	Example: 
	1: cd /folder/with/files & folders
	2: $( basename ${0} )
	
	"
}

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Executive                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

if [[ $1 == "--help" ]]; then
	local::_help
	exit 0
fi

# Ensure access to the rtd library functions:
dependency::_library || { echo -e "RTD functions NOT found!"; exit 1; }

# call compression function with its default behavior...
compress_all_items_here || { write_error -e "Compression failed!"; exit 1; }