#!/bin/bash

:${Region:="NorthEurope"}
:${MyResourceGroup}

azure_create_resource_group ()
{
        az group create -l ${Region} -n ${MyResourceGroup}
}


azure_list_subscriptions ()
{
        azure-cli account list|grep name| grep -v onmicrosoft.com|cut -d: -f2|cut -d, -f1
}


