#!/bin/bash
#
#::                                     A D M I N   C O M M A N D L E T   
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
#::
#:: Author:   	SLS
#:: Version 	1.00
#::
#::
#::	Purpose: The purpose of this script is to monitor a linux system interactively.  
#::		 This may be useful for trouble shooting.
#::		
#::     Usage:	Simply execute this commandlet to accomplith this task.
#:: 		
#::     	
#::     	
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Lunches 4 Xterm windows and starts system monitoring tool in them. This is intended to demonstrate how to 
# launch windows from the ternminal and determin where on the screen they should appear. 
#
# Xterm obeys the following on screen positions:
#
# +0+0    upper left hand corner.
# -0+0    upper right hand corner.
# -0-0    lower right hand corner.
# +0-0    lower left hand corner.


xterm  -geometry 110x30+0+0 -e 'htop' &
xterm  -geometry 110x30-0+0 -e 'tail -f /var/log/syslog' &
xterm  -geometry 110x30-0-0 -e 'watch df -h '&
xterm  -geometry 110x30+0-0 -e 'bmon' &
