#!/bin/bash
#
#::                                    A D M I N   C O M M A N D
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
#::
#:: Author:   	SLS
#:: Version 	1.02
#::
#::
#::	Purpose: The purpose of this script is to migrate a users dropbox folder to a volume
#::		 that is loopmounted and formatted with extfs4. This may be needed if the dropbox folder
#::		 needs to reside on a Luks encrypted home folder; wich Dropbox has dropped support for.
#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
#::
#::
#::
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.



if [[ -d ~/Dropbox ]]; then
        killall dropbox
        mv Dropbox Dropbox.bak
        mkdir Dropbox
        dd if=/dev/zero of=~/.dropbox/storage bs=1M count=14072
        mkfs.ext4 /home/$USER/.dropbox/storage
        chattr +i /home/$USER/Dropbox
        /home/$USER/.dropbox/storage /home/$USER/Dropbox ext4 defaults,user_xattr,loop 0 0
        mount /home/$USER/Dropbox/


        chown -R $USER /home/$USER/Dropbox
        cp -a Dropbox.bak/* Dropbox/
else
        echo "Dropbox folder not found!"
        exit 1
fi