#!/bin/bash
PUBLICATION="RTD Simple User Configuration Backup Tool"
VERSION="1.00"
#
#::             RTD Ubuntu + derivatives backup script
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
#::
#::     Author:   	SLS
#::     Version 	1.02
:	${GIT_Profile:=vonschutter}
#::
#::	Purpose: The purpose of the script is to backup a users setings
#::              and dokuments to some useful location.
#::
#::	Value: Useful when preserving user-specific desktop settings, credentials,
#::	       documents, and related profile data before reinstall, migration,
#::	       repair work, or major system changes.
#::
#::	Usage: Run the script and follow the prompts to choose what should be
#::	       backed up and where the resulting archive set should be written.
#::
#::	Examples:
#::	       rtd-oem-backup-linux-config
#::	       sudo rtd-oem-backup-linux-config
#::
#:: This system configuration and installation script was originally developed
#:: for RuntimeData, a small OEM in Buffalo Center, IA.
#::
#:: RTD admin scrips are placed in /opt/rtd/scripts. This configuration script is mainly built to use
#:: functions in _rtd_functions and _rtd_recipies.
#::       _rtd_functions -- contain usefull admin functions for scripts, such as "how to install software" on different systems.
#::
#::
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Settings                 ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
# You may comment out or edit items as you deem necessary.
# Ensure that the  RTD Functions are available and load them...
# This contains most of the intelligence used to perform this systems
# maintenance.


# Set the background tilte:
BACKTITLE="$PUBLICATION"

# Set the options to appear in the menu as choices:
option_1="Gnome Desktop Setings"
option_2="Gnome Credentials Manager"
option_3="Remmina Configuration"
option_4="Users Private Themes"
option_5="Users Private Icons"
option_6="Users Private Fonts "
option_7="Users Private Documents"
option_8="Users Private Pictures"
option_9="Firefox Settings"
option_10="Chrome Settings"
option_11="All VirtualBox VMs"
option_12="Teamviewer Configuration"
option_13="Backup entire HOME folder"
option_14="Backup All Virtual Machines (KVM)"





#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Functions                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

rtd::bootstrap_library() {
	local library_name="${1:-_rtd_library}"
	local minimum_version="${2:-}"
	local loaded_version="${RTD_VERSION:-${RTDFUNCTIONS:-}}"
	local script_dir path src_url tmp

	if [[ "$library_name" == "_rtd_library" && -n "$loaded_version" ]]; then
		if { [[ -z "$minimum_version" ]] || [[ "$(printf '%s\n%s\n' "$minimum_version" "$loaded_version" | sort -V | tail -n 1)" == "$loaded_version" ]]; } &&
			declare -F system::log_item >/dev/null 2>&1 &&
			declare -F library::apply_rtd_defaults >/dev/null 2>&1; then
			return 0
		fi
	fi

	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	for path in \
		"${script_dir}/${library_name}" \
		"${script_dir}/../core/${library_name}" \
		"${script_dir}/../../core/${library_name}" \
		"/opt/${_TLA:-${_tla:-rtd}}/core/${library_name}" \
		"/opt/rtd/core/${library_name}" \
		"${HOME:-}/GIT/RTD-Setup/core/${library_name}" \
		"${HOME:-}/RTD-Setup/core/${library_name}"; do
		if [[ -r "$path" ]]; then
			# shellcheck source=/dev/null
			source "$path" ""
			return $?
		fi
	done

	src_url="https://github.com/${_GIT_PROFILE:-${GIT_Profile:-vonschutter}}/RTD-Setup/raw/main/core/${library_name}"
	tmp="$(mktemp "/tmp/${library_name}.XXXXXX" 2>/dev/null || echo "/tmp/${library_name}.$$")"
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$src_url" -o "$tmp" || return 1
	elif command -v wget >/dev/null 2>&1; then
		wget -qO "$tmp" "$src_url" || return 1
	else
		return 1
	fi

	# shellcheck source=/dev/null
	source "$tmp" ""
	local rc=$?
	rm -f "$tmp"
	return $rc
}


# Function to request an encryption phrase.
# This prase will be used to encrypt the compressed archives.
zenity_ask_for_encryption_pass_phrase () {
	software::check_native_package_dependency zenity
    	passtoken=$(zenity --title "Encryption Password" --password )
    	if [[ -z "$passtoken" ]]; then
                zenity --warning --text="Your settings likely contain sensitive information and should be encrypted! Please set a pass phrase"
		zenity_ask_for_encryption_pass_phrase
        fi
}



# Function to display the backup otions above. This is all done in a bit of a
# round about way... but the idea is to prepare this setup to be flexible
# for the future so that you only have one place to list the option while
# more than one gui toolkit (dialog, zenity, whiptail) depending on your environment.
zenity_show_list_of_user_backup_choices () {
        cmd=( zenity  --list  --width=800 --height=400 --text "Please Select Whant to Backup" --title "$BACKTITLE" --checklist  --column "ON/OFF" --column "What to backup" --separator "," )
        zstatus=FALSE
        options=(    $zstatus "$option_1"
                     $zstatus "$option_2"
                     $zstatus "$option_3"
                     $zstatus "$option_4"
                     $zstatus "$option_5"
                     $zstatus "$option_6"
                     $zstatus "$option_7"
                     $zstatus "$option_8"
                     $zstatus "$option_9"
                     $zstatus "$option_10"
                     $zstatus "$option_11"
                     $zstatus "$option_12"
		     $zstatus "$option_13"
		     $zstatus "$option_14"
                   )

       choices=$("${cmd[@]}" "${options[@]}" )
}




# Simple function to display a infromational notice when the tool is envoked.
rtd_oem_user_backup_info_notice() {

	zenity --info --width=800 --height=400 --text="

The RTD User Backup tool is a simple tool to allow anyone to backup important files and/or the entire home folder to an external USB drive as a backup ahead of re-installing a PC from scratch.

It is highly recommended to encrypt all content so that is cannot easily be stolen. Do remember the password or you will never be able to access the backed-up content ever again.

You will need the following:
1 - An external drive
2 - A good password

The RTD Backup tool will encrypt, compress and save all the information in the location provided.
	"
}



# Dialog to request the destination of where to store the compressed and encrypted archive.
rtd_oem_request_user_backup_destination() {
	if [[ -z "$rtd_oem_user_backup_destination" ]]; then
		export rtd_oem_user_backup_destination=$( zenity --width=800 --height=400 --text "$BACKTITLE" --file-selection --directory  )
	elif [[ -n "$string" ]]; then
		echo "Saving Backup to: $rtd_oem_user_backup_destination"
	fi
}



# Notify end user thes backup tasks are complete.
rtd_oem_user_backup_info_notice_complete() {
	zenity --info --width=800 --height=400 --text="
Backup is complete. Please revise the list below.

Backup archive(s) saved to:
$rtd_oem_user_backup_destination

Archives:
$(ls $rtd_oem_user_backup_destination/*.7z )
"
}



# Cleanup any potential junk left in the environment.
rtd_oem_cleanup() {

	unset rtd_oem_user_backup_destination
	unset passtoken
}



# Function to execute the given backup and encryption task. Levels of compression and
# other option may be set in the seting section of this script (tool)
rtd_user_bak () {
	rtd_oem_request_user_backup_destination
	echo ... > $rtd_oem_user_backup_destination/flg
	if [[ -e $rtd_oem_user_backup_destination/flg ]]; then
		rm $rtd_oem_user_backup_destination/flg
		if [[ -d $2 ]]; then
			7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p$passtoken $rtd_oem_user_backup_destination/`whoami`-"$1"-`date -u --iso-8601`.7z "${@:2}"
		else
			echo "Backup source $2 does not exist..."
		fi
	else
		zenity --info --width=800 --height=400 --text="$rtd_oem_user_backup_destination is not writable! Plese select another destination."
		rtd_oem_request_user_backup_destination
	fi
}



# Function to do what the choices instruct. We read the output from
# the choices and execute commands that accomplish the task requested.
do_instructions_from_choices (){
        IFS=$','
	for choice in $choices
	do
		case $choice in
	        "$option_1") rtd_user_bak "$option_1" ~/Templates ;;
		"$option_2") rtd_user_bak "$option_2" ~/Templates ;;
		"$option_3") rtd_user_bak "$option_3" ~/.local/share/remmina ~/.config/remmina	;;
		"$option_4") rtd_user_bak "$option_4" ~/.themes ;;
		"$option_5") rtd_user_bak "$option_5" ~/.icons ;;
		"$option_6") rtd_user_bak "$option_6" ~/.fonts	;;
		"$option_7") rtd_user_bak "$option_7" ~/Documents ;;
		"$option_8") rtd_user_bak "$option_8" ~/Pictures ;;
		"$option_9") rtd_user_bak "$option_9" ~/Templates ;;
		"$option_10") rtd_user_bak "$option_10" ~/.config/google-chrome/Default/Preferences ;;
		"$option_11") rtd_user_bak "$option_11" "~/VirtualBox VM's" ;;
		"$option_12") rtd_user_bak "$option_12" ~/.config/teamviewer ;;
		"$option_13") rtd_user_bak "$option_13" $HOME ;;
		"$option_14")
			echo $passtoken |sudo -S chmod 777 -R /var/lib/libvirt
			rtd_user_bak "$option_14" /var/lib/libvirt
			echo $passtoken |sudo -S  chmod 750 -R /var/lib/libvirt
			echo $passtoken |sudo -S  chown -R libvirt-qemu /var/lib/libvirt
		;;
		esac
	done
}



#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Sript Flow Control              ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
# Software and configuration selections dialog. This will present a number of OEM defaults
# and other preferences that can be added to a system at will. To remove software it is
# recommended to use the native software tool (Gnome Software, Yast, or Discover).
#
# Option defaults may be set to "on" or "off"

# "dialog" will be used to request interactive configuration...
# Ensure that it is available:
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
	cat <<EOF
Usage:
  $(basename "$0") [--help|-h]

Description:
  Open the RTD Linux configuration backup workflow and guide you through the backup selections.
EOF
	exit 0
fi

trap "passtoken=nonsense" 0 1 2 5 15
rtd::bootstrap_library "_rtd_library" || { echo "Failed to load _rtd_library"; exit 1; }
rtd_oem_user_backup_info_notice
zenity_ask_for_encryption_pass_phrase
zenity_show_list_of_user_backup_choices
do_instructions_from_choices
rtd_oem_user_backup_info_notice_complete




#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Finalize.....                   ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
rtd_oem_cleanup
exit











