#!/bin/bash
PUBLICATION="RuntimeData Update Manager for Ubuntu"
VERSION="1.13"
#
#	RTD Ubuntu + derivatives software update script
#
#
# This system configuration and installation script was originally developed
# for RuntimeData, a small OEM in Buffalo Center, IA. The purpose of the script
# was to install and configure Ubuntu and Zorin OS PC's. This OEM and store nolonger
# exists as its owner has passed away. This script is shared in the hopes that
# someone will find it usefull.
#
# The purpose of this script is to update installed software from distribution reopositories.
#
###########################################################################
##                                                                       ##
##                       Set Environment                                 ##
##                                                                       ##
###########################################################################
# Test comment...
# Set colors for prompting on screen.
	YELLOW="\033[1;33m"
	RED="\033[1;31m"
	ENDCOLOR="\033[0m"
	GREEN="\033[1;32m"
	BLUE="\033[1;34m"
	
# Ensure administrative privileges.
[ "$UID" -eq 0 ] && echo -e "Administrative Access OK" $ENDCOLOR || echo -e $YELLOW"This script needs administrative access..." $ENDCOLOR 
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Identify 
# clear	
echo -e $GREEN"$PUBLICATION: Version $VERSION" $ENDCOLOR
echo -e $GREEN"--------------------------------------------------------" $ENDCOLOR

echo This tool makes it simple to update software from all channels 
echo available on the system at once. It will update via the native
echo -e "package manager as well as newer formats like $YELLOW"snap"$ENDCOLOR and $YELLOW"flatpak"$ENDCOLOR..."
echo " " 
echo This update script supports the following instructions:
echo " "
echo -e " - $YELLOW"Default"$ENDCOLOR : Just running this script will update via all configured channels."	
echo -e " - $YELLOW"update"$ENDCOLOR :  Parameter "update" will update the updater to the latest version. "
echo -e " - $YELLOW"setup"$ENDCOLOR :   Parameter "setup" make sure that you are using all software channels "
echo -e "      "
echo " "

if [ "$1" == "update" ]; then 
       	INSTRUCTION=update_me
fi

if [ "$1" == "config" ]; then 
       	INSTRUCTION=config_me
fi

if [ "$1" == "setup" ]; then 
       	INSTRUCTION=setup_me
fi



# Enable RTD Functions...
echo "Checking for RTD Functions..."
FILE=/opt/rtd/scripts/_rtd_library
if [ -f $FILE ]; then
   echo -e $GREEN"RTD Functions are available: Loading them for use... " $ENDCOLOR
   source $FILE
else
   echo "Cannot find RTD Functions... Attempting to get them online... "
   wget -q --show-progress https://github.com/vonschutter/RTD-Build/raw/master/"${FILE##*/}" -P /opt/rtd/scripts
   if [ -f $FILE ]; then
   	echo -e $GREEN"RTD Functions are available: Loading them for use... " $ENDCOLOR
   	source $FILE
   else
   	echo -e $RED"RTD Functions could NOT be loaded; You must use the native options to install software... "$ENDCOLOR
   	exit 
   fi
fi





###########################################################################
##                                                                       ##
##                         Functions                                     ##
##                                                                       ##
###########################################################################
#




log_item ()
{
DATE=$(date '+%d/%m/%Y %H:%M:%S');
echo "$DATE --- : $@" >> $0.log
}



update_me ()
{
	rm $0.bak
	mv $0 $0.bak
        wget  --show-progress https://github.com/vonschutter/RTD-Build/raw/master/System_Update/${0##*/} -P ${0%/*} 
        chmod +x $0
        if [[ -e $0 ]]; then 
        	return  0 
        else
        	cp $0.bak $0
        	return 1 
        fi 
}



config_me ()
{
	write_error "::There is nothing to configure at this time!::"
}



setup_me ()
{
	check_dependencies flatpak
	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	check_dependencies  snapd
}

###########################################################################
##                                                                       ##
##                        Execute updates                                ##
##                                                                       ##
###########################################################################
#
#

# Execute the fist instruction passed to this script... 
if [ ! -z $INSTRUCTION ]; then
	log_item The instruction $INSTRUCTION was given... 
	$INSTRUCTION
	exit
else
	log_item No instructions passed to $0... Continuing with default behavior. 
fi

write_status "Updating installed software..." 

# Updating software managed by distribution speciffic software manager...
# Unless the RTD Functions are loaded, then use that. 

rtd_update_system





